version: "3.8"

services:
  indicator-service:
    build: .
    container_name: indicator-service
    restart: always
    environment:
      - REDIS_HOST=indicators-redis
      - REDIS_PORT=6379
    depends_on:
      - indicators-redis
      - indicators-mongo

  indicators-redis:
    image: "redis:alpine"
    container_name: indicators-redis
    restart: always

  indicators-mongo:
    image: "mongo:latest"
    container_name: indicators-mongo
    restart: always
