services:
  indicator-service:
    build: .
    container_name: indicator-service
    restart: always
    environment:
      - REDIS_HOST=indicators-redis
      - REDIS_PORT=6379
      - MONGO_URI=mongodb://indicators-mongo/indicators
    depends_on:
      - indicators-redis
      - indicators-mongo
    develop:
      watch:
        - action: sync
          path: ./app
          target: /app
          ignore:
            - __pycache__/
        - action: rebuild
          path: requirements.txt

  indicators-redis:
    image: "redis:alpine"
    container_name: indicators-redis
    restart: always

  indicators-mongo:
    image: "mongo:latest"
    container_name: indicators-mongo
    environment:
      MONGO_INITDB_DATABASE: indicators
    volumes:
      - indicators_db:/data/db

volumes:
  indicators_db:
